utf8_spanish2_ci
CREATE TABLE `TORNEO`( 
    `ID_TORNEO` INT NOT NULL AUTO_INCREMENT, 
    `ANIO_TORNEO` INT NOT NULL, 
    PRIMARY KEY (`ID_TORNEO`), 
    UNIQUE (`ANIO_TORNEO`)
);
    
CREATE TABLE `GRUPO`( 
    `ID_GRUPO` INT NOT NULL AUTO_INCREMENT, 
    `GENERO_GRUPO` BIT NOT NULL,
    `IDENTIFICADOR_GRUPO` VARCHAR(2) NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_GRUPO`), 
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE  
);

CREATE TABLE `SECCION`( 
    `ID_SECCION` INT NOT NULL AUTO_INCREMENT, 
    `NOMBRE_SECCION` VARCHAR(7) NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_SECCION`), 
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE  
);
    
CREATE TABLE `EQUIPO`( 
    `ID_EQUIPO` INT NOT NULL AUTO_INCREMENT, 
    `NOMBRE_EQUIPO` VARCHAR(35) NOT NULL,
    `GENERO_EQUIPO` BIT NOT NULL,
    `ID_SECCION` INT NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_EQUIPO`),
    FOREIGN KEY (`ID_SECCION`) REFERENCES `SECCION`(`ID_SECCION`) ON DELETE RESTRICT ON UPDATE CASCADE, 
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `GRUPO_EQUIPO`( 
    `ID_GRUPO_EQUIPO` INT NOT NULL AUTO_INCREMENT, 
    `ID_EQUIPO` INT NOT NULL,
    `ID_GRUPO` INT NOT NULL,
    PRIMARY KEY (`ID_GRUPO_EQUIPO`),
    FOREIGN KEY (`ID_EQUIPO`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE, 
    FOREIGN KEY (`ID_GRUPO`) REFERENCES `GRUPO`(`ID_GRUPO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `JUGADOR`( 
    `ID_JUGADOR` INT NOT NULL AUTO_INCREMENT,
    `NOMBRES` VARCHAR(45) NOT NULL,
    `APELLIDOS` VARCHAR(45) NOT NULL,
    `NIE` INT NOT NULL, 
    `GENERO_JUGADOR` BIT NOT NULL,
    `FECHA_NACIMIENTO_JUGADOR` DATE NOT NULL,
    `NUMERO_JUGADOR` INT NOT NULL,
    `ID_EQUIPO` INT NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_JUGADOR`),
    FOREIGN KEY (`ID_EQUIPO`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE,   
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE  
);

CREATE TABLE `TIPO_SANCION_ADMIN`(
    `ID_TIPO_SANCION_ADMIN` INT NOT NULL AUTO_INCREMENT,
    `TIPO_SANCION_ADMINISTRATIVA` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID_TIPO_SANCION_ADMIN`)
);

CREATE TABLE `SANCION_ADMINISTRATIVA`( 
    `ID_SANCION_ADMINISTRATIVA` INT NOT NULL AUTO_INCREMENT,
    `FECHA_INI_SANCION_ADMIN` DATE NOT NULL,
    `FECHA_FIN_SANCION_ADMIN` DATE NOT NULL,
    `COMENTARIO_SANCION_ADMIN` VARCHAR(150) NOT NULL, 
    `ID_JUGADOR` INT NOT NULL,
    `ID_TIPO_SANCION_ADMIN` INT NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_SANCION_ADMINISTRATIVA`),
    FOREIGN KEY (`ID_JUGADOR`) REFERENCES `JUGADOR`(`ID_JUGADOR`) ON DELETE RESTRICT ON UPDATE CASCADE,   
    FOREIGN KEY (`ID_TIPO_SANCION_ADMIN`) REFERENCES `TIPO_SANCION_ADMIN`(`ID_TIPO_SANCION_ADMIN`) ON DELETE RESTRICT ON UPDATE CASCADE,   
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE  
);

CREATE TABLE `ORIENTADOR`( 
    `ID_ORIENTADOR` INT NOT NULL AUTO_INCREMENT, 
    `NOMBRES_ORIENTADOR` VARCHAR(45) NOT NULL,
    `APELLIDOS_ORIENTADOR` VARCHAR(45) NOT NULL,
    `GENERO_ORIENTADOR` BIT NOT NULL,
    PRIMARY KEY (`ID_ORIENTADOR`)
);

CREATE TABLE `ARBITRO`( 
    `ID_ARBITRO` INT NOT NULL AUTO_INCREMENT, 
    `NOMBRES_ARBITRO` VARCHAR(45) NOT NULL,
    `APELLIDOS_ARBITRO` VARCHAR(45) NOT NULL,
    `GENERO_ARBITRO` BIT NOT NULL,
    PRIMARY KEY (`ID_ARBITRO`)
);

CREATE TABLE `CANCHA`( 
    `ID_CANCHA` INT NOT NULL AUTO_INCREMENT, 
    `NOMBRE_CANCHA` VARCHAR(45) NOT NULL,
    `UBICACION_CANCHA` VARCHAR(150) NOT NULL,
    PRIMARY KEY (`ID_CANCHA`)
); 

CREATE TABLE `JORNADA`(
    `ID_JORNADA` INT NOT NULL AUTO_INCREMENT,
    `NUM_JORNADA` INT NOT NULL,
    `ID_GRUPO` INT NOT NULL,
    PRIMARY KEY (`ID_JORNADA`),
    FOREIGN KEY (`ID_GRUPO`) REFERENCES `GRUPO`(`ID_GRUPO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `DETALLE_JORNADA`(
    `ID_DETALLE_JORNADA` INT NOT NULL AUTO_INCREMENT,
    `ID_EQUIPO1` INT NOT NULL,
    `ID_EQUIPO2` INT NOT NULL,
    `ID_PARTIDO` INT NOT NULL,
    `ID_JORNADA` INT NOT NULL,
    PRIMARY KEY (`ID_DETALLE_JORNADA`),
    FOREIGN KEY (`ID_EQUIPO1`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_EQUIPO2`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_JORNADA`) REFERENCES `JORNADA`(`ID_JORNADA`) ON DELETE RESTRICT ON UPDATE CASCADE
);
    
CREATE TABLE `PARTIDO`(
    `ID_PARTIDO` INT NOT NULL AUTO_INCREMENT,
    `NUM_PARTIDO` INT,
    `FECHA` DATE,
    `HORA` TIME,
    `ESTADO_PARTIDO` INT NOT NULL DEFAULT 0,
    `ID_EQUIPO1` INT NOT NULL,
    `ID_EQUIPO2` INT NOT NULL,
    `ID_CANCHA` INT,
    `ID_JORNADA` INT NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_PARTIDO`),
    FOREIGN KEY (`ID_EQUIPO1`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_EQUIPO2`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_CANCHA`) REFERENCES `CANCHA`(`ID_CANCHA`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_JORNADA`) REFERENCES `JORNADA`(`ID_JORNADA`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `CHK_ESTADO_PARTIDO` CHECK (`ESTADO_PARTIDO` = 0 OR `ESTADO_PARTIDO` = 1 OR `ESTADO_PARTIDO` = 2)
);

CREATE TABLE `PARTIDO_ORIENTADOR`( 
    `ID_PARTIDO_ORIENTADOR` INT NOT NULL AUTO_INCREMENT, 
    `ID_ORIENTADOR1` INT NOT NULL,
    `ID_ORIENTADOR2` INT NOT NULL,
    `ID_PARTIDO` INT NOT NULL,
    PRIMARY KEY (`ID_PARTIDO_ORIENTADOR`),
    FOREIGN KEY (`ID_ORIENTADOR1`) REFERENCES `ORIENTADOR`(`ID_ORIENTADOR`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_ORIENTADOR2`) REFERENCES `ORIENTADOR`(`ID_ORIENTADOR`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_PARTIDO`) REFERENCES `PARTIDO`(`ID_PARTIDO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `PARTIDO_ARBITRO`( 
    `ID_PARTIDO_ARBITRO` INT NOT NULL AUTO_INCREMENT,
    `ID_ARBITRO_PRINCIPAL` INT NOT NULL, 
    `ID_ARBITRO_ASISTENTE` INT NOT NULL,
    `ID_PARTIDO` INT NOT NULL,
    PRIMARY KEY (`ID_PARTIDO_ARBITRO`),
    FOREIGN KEY (`ID_ARBITRO_PRINCIPAL`) REFERENCES `ARBITRO`(`ID_ARBITRO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_ARBITRO_ASISTENTE`) REFERENCES `ARBITRO`(`ID_ARBITRO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_PARTIDO`) REFERENCES `PARTIDO`(`ID_PARTIDO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `DETALLE_PARTIDO`(
    `ID_DETALLE_PARTIDO` INT NOT NULL AUTO_INCREMENT,
    `NUM_GOLES` INT,
    `ID_JUGADOR` INT NOT NULL,
    `ID_EQUIPO` INT NOT NULL,
    `ID_PARTIDO` INT NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_DETALLE_PARTIDO`),
    FOREIGN KEY (`ID_JUGADOR`) REFERENCES `JUGADOR`(`ID_JUGADOR`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_EQUIPO`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE,   
    FOREIGN KEY (`ID_PARTIDO`) REFERENCES `PARTIDO`(`ID_PARTIDO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `TARJETA_ROJA`(
    `ID_TARJETA_ROJA` INT NOT NULL AUTO_INCREMENT,
    `TIPO` BIT NOT NULL,
    `ESTADO_TAR_ROJA` BIT NOT NULL,
    `PARTIDOS_NO_JUGADOS_TAR_ROJA` INT NOT NULL,
    `ID_JUGADOR` INT NOT NULL,
    `ID_PARTIDO` INT NOT NULL,
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_TARJETA_ROJA`),
    FOREIGN KEY (`ID_JUGADOR`) REFERENCES `JUGADOR`(`ID_JUGADOR`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_PARTIDO`) REFERENCES `PARTIDO`(`ID_PARTIDO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `TARJETA_AMARILLA`(
    `ID_TAR_AMAR` INT NOT NULL AUTO_INCREMENT,
    `ESTADO_TAR_AMAR` BIT NOT NULL,
    `ID_JUGADOR` INT NOT NULL,
    `ID_PARTIDO` INT NOT NULL,   
    `ID_TORNEO` INT NOT NULL,
    PRIMARY KEY (`ID_TAR_AMAR`),
    FOREIGN KEY (`ID_JUGADOR`) REFERENCES `JUGADOR`(`ID_JUGADOR`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_PARTIDO`) REFERENCES `PARTIDO`(`ID_PARTIDO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_TORNEO`) REFERENCES `TORNEO`(`ID_TORNEO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `TABLA_POSICIONES`(
    `ID_TABLA_POSICIONES` INT NOT NULL AUTO_INCREMENT,
    `ID_GRUPO` INT NOT NULL,
    PRIMARY KEY (`ID_TABLA_POSICIONES`),
    FOREIGN KEY (`ID_GRUPO`) REFERENCES `GRUPO`(`ID_GRUPO`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `DETALLE_TABLA_POSICIONES`(
    `ID_DETALLE_TABLA_POSICIONES` INT NOT NULL AUTO_INCREMENT,
    `PARTIDOS_JUGADOS` INT NOT NULL,
    `PARTIDOS_GANADOS` INT,
    `PARTIDOS_EMPATADOS` INT, 
    `PARTIDOS_PERDIDOS` INT,
    `GOLES_FAVOR` INT,
    `GOLES_CONTRA` INT,
    `ID_EQUIPO` INT NOT NULL,
    `ID_TABLA_POSICIONES` INT NOT NULL,
    PRIMARY KEY (`ID_DETALLE_TABLA_POSICIONES`),
    FOREIGN KEY (`ID_EQUIPO`) REFERENCES `EQUIPO`(`ID_EQUIPO`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ID_TABLA_POSICIONES`) REFERENCES `TABLA_POSICIONES`(`ID_TABLA_POSICIONES`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `USUARIO`( 
    `ID_USUARIO` INT NOT NULL AUTO_INCREMENT, 
    `NOMBRE_USUARIO` VARCHAR(25) NOT NULL, 
    `CONTRASENIA` VARCHAR(255) NOT NULL, 
    PRIMARY KEY (`ID_USUARIO`) 
);